pass:
  build: .
  restart: always
  cpu_shares: 128
  mem_limit: 64m
  environment:
    - AWS_ACCESS_KEY_ID=changeme
    - AWS_SECRET_ACCESS_KEY=changeme
    - S3_BUCKET=vizzbuzz
    - DEPLOY_ENV=dev
  volumes:
    - ./s3-conf-test:/conf

test:
  image: alpine
  command: sh -c "sleep 10; $(cat /conf/env.sh); set; ls -l /conf/* "
  environment:
    - S3_CONF_KEY=test-key
  volumes:
    - ./s3-conf-test:/conf:ro

